import type { Request, Response } from 'express';
import pool from '../config/database.js';

// GET handler to list blocked domains from the database for the current tenant
export async function getBlockedDomains(req: Request, res: Response) {
  try {
    const tenantId = req.user?.tenantId;
    if (!tenantId) {
      return res.status(403).json({ error: 'Forbidden: Tenant ID is missing.' });
    }
    const result = await pool.query(
      'SELECT * FROM blocked_domains WHERE tenant_id = $1 ORDER BY "blockedAt" DESC',
      [tenantId]
    );
    res.status(200).json(result.rows);
  } catch (error) {
    console.error('Error in getBlockedDomains:', error);
    const message = error instanceof Error ? error.message : 'An unknown error occurred.';
    res.status(500).json({ error: 'Failed to retrieve blocked domains.', details: message });
  }
}

// POST handler to add a new blocked domain to the database for the current tenant
export async function addBlockedDomain(req: Request, res: Response) {
  try {
    const tenantId = req.user?.tenantId;
    if (!tenantId) {
      return res.status(403).json({ error: 'Forbidden: Tenant ID is missing.' });
    }
    const { domain } = req.body;
    if (!domain || typeof domain !== 'string') {
      return res.status(400).json({ error: 'Domain is required and must be a string.' });
    }

    const result = await pool.query(
      'INSERT INTO blocked_domains (domain, tenant_id) VALUES ($1, $2) RETURNING *',
      [domain, tenantId]
    );

    res.status(201).json(result.rows[0]);
  } catch (error) {
    console.error('Error in addBlockedDomain:', error);
    const message = error instanceof Error ? error.message : 'An unknown error occurred.';
    // Handle potential unique constraint violation (duplicate domain for the same tenant)
    if (error instanceof Error && 'code' in error && error.code === '23505') {
      return res
        .status(409)
        .json({ error: 'This domain is already in the blocklist for this tenant.' });
    }
    res.status(500).json({ error: 'Failed to add blocked domain.', details: message });
  }
}

// DELETE handler to remove a blocked domain from the database for the current tenant
export async function removeBlockedDomain(req: Request, res: Response) {
  try {
    const tenantId = req.user?.tenantId;
    if (!tenantId) {
      return res.status(403).json({ error: 'Forbidden: Tenant ID is missing.' });
    }
    const { id } = req.params;
    const result = await pool.query(
      'DELETE FROM blocked_domains WHERE id = $1 AND tenant_id = $2',
      [id, tenantId]
    );

    // Check for rowCount being non-null before comparing
    if (result.rowCount && result.rowCount > 0) {
      res.status(204).send(); // Success, no content
    } else {
      res.status(404).json({ error: 'Domain with the specified ID not found for this tenant.' });
    }
  } catch (error) {
    console.error('Error in removeBlockedDomain:', error);
    const message = error instanceof Error ? error.message : 'An unknown error occurred.';
    res.status(500).json({ error: 'Failed to remove blocked domain.', details: message });
  }
}

// GET handler to generate an RPZ zone file for the current tenant
export async function generateRpzZoneFile(req: Request, res: Response) {
  try {
    const tenantId = req.user?.tenantId;
    if (!tenantId) {
      return res.status(403).json({ error: 'Forbidden: Tenant ID is missing.' });
    }

    const result = await pool.query(
      'SELECT domain FROM blocked_domains WHERE tenant_id = $1 ORDER BY domain ASC',
      [tenantId]
    );

    const domains: string[] = result.rows.map((row) => row.domain);

    // Generate a serial number based on the current date and time (YYYYMMDDHH)
    const serial = new Date()
      .toISOString()
      .replace(/[^0-9]/g, '')
      .slice(0, 10);

    // Standard SOA record for an RPZ file
    let rpzContent = `$TTL 1h\n`;
    rpzContent += `@ IN SOA localhost. root.localhost. (${serial} 1h 15m 30d 2h)\n`;
    rpzContent += `  IN NS  localhost.\n`;
    rpzContent += `;\n; RPZ zone file generated by NOC AI for tenant ${tenantId}\n;\n`;

    // Add domain entries
    domains.forEach((domain) => {
      rpzContent += `${domain} CNAME .\n`;
      rpzContent += `*.${domain} CNAME .\n`;
    });

    res.status(200).json({ rpzContent });
  } catch (error) {
    console.error('Error in generateRpzZoneFile:', error);
    const message = error instanceof Error ? error.message : 'An unknown error occurred.';
    res.status(500).json({ error: 'Failed to generate RPZ zone file.', details: message });
  }
}
